spring:
  profiles:
    active: local
  application:
    name: handy-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  address: 0.0.0.0

jwt:
  secret: your-secret-key-should-be-at-least-32-characters-long
  expiration: 86400000 # 24시간 (밀리초 단위)

logging:
  level:
    root: INFO
    com.handy.appserver: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
      presigned-url:
        expiration: 3600000  # 1시간 